---
- hosts: servidores
  become: true
  tasks:
    - name: Copiando WAR remotamente al Server Docker
      copy:
        src: /home/ansibleadmin/carpeta_de_wars/*.war
        dest: /home/ansibleadmin/carpeta_de_wars/
        owner: ansibleadmin
        group: sudo
        mode: 0644
