---
- hosts: kubernetes
  become: true
  tasks:
    - name: Copia WAR remotamente al Servidor Docker
      copy:
        src: /home/ansibleadmin/carpeta_de_wars/devops-vinceup-hell-yeah.war
        dest: /home/dockeradmin/carpeta_de_wars/
